import mongoose from 'mongoose'

const personSchema = new mongoose.Schema({
  itemNumber: { type: String, default: '' },
  personDocLink: { type: String, default: '' },
  firstName: { type: String, default: '' },
  middleName: { type: String, default: '' },
  lastName: { type: String, default: '' },
  suffix: { type: String, default: '' },
  address: { type: String, default: '' },
  city: { type: String, default: '' },
  state: { type: String, default: '' },
  zip: { type: String, default: '' },
  internationalAddress: { type: String, default: '' },
  country: { type: String, default: '' },
  dob: { type: String, default: '' },
  ssn: { type: String, default: '' },
  tin: { type: String, default: '' },
  financialAccountNumber: { type: String, default: '' },
  financialRoutingNumberInternal: { type: String, default: '' },
  financialRoutingNumber: { type: String, default: '' },
  financialInstitutionName: { type: String, default: '' },
  loginPlatform: { type: String, default: '' },
  paymentCardNumber: { type: String, default: '' },
  paymentCardExpirationDate: { type: String, default: '' },
  passportNumber: { type: String, default: '' },
  passportIssuingCountry: { type: String, default: '' },
  passportExpirationDate: { type: String, default: '' },
  militaryIdNumber: { type: String, default: '' },
  driversLicenseNumber: { type: String, default: '' },
  dlState: { type: String, default: '' },
  otherGovernmentIssuedIdNumber: { type: String, default: '' },
  otherGovIdNumber: { type: String, default: '' },
  otherGovernmentIssuedType: { type: String, default: '' },
  otherGovIdType: { type: String, default: '' },
  otherGovernmentIssuedIdCountry: { type: String, default: '' },
  otherGovIdCountry: { type: String, default: '' },
  studentIdNumber: { type: String, default: '' },
  alienRegistrationNumber: { type: String, default: '' },
  tribalIdentificationNumber: { type: String, default: '' },
  tribalIdNumber: { type: String, default: '' },
  stateIdentificationCardNumber: { type: String, default: '' },
  stateIdCardNumber: { type: String, default: '' },
  patientAccountNumber: { type: String, default: '' },
  medicalRecordNumber: { type: String, default: '' },
  medicaidMedicareNumber: { type: String, default: '' },
  healthInsurancePolicyNumber: { type: String, default: '' },
  dateOfDeath: { type: String, default: '' },
  dataOwner: { type: String, default: '' },
  role: { type: String, default: '' },
  hospital: { type: String, default: '' },
  createdBy: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now },
  updatedBy: { type: String, default: '' },
  updatedAt: { type: Date, default: Date.now },
}, { _id: false, strict: false })

const codingSchema = new mongoose.Schema({
  projectId: { type: String, required: true, index: true },
  documentId: { type: String, required: true, index: true },
  alDesignation: { type: String, default: 'Relevant' },
  flrComplete: { type: String, default: 'Yes' },
  reportableDataFound: { type: String, default: 'Alternate Workflow 6+ Entries' },
  extractionStatus: { type: String, default: 'Completed' },
  alternateWorkflowEstimate: { type: String, default: '6 - 25 Entries' },
  alternateWorkflowComplete: { type: String, default: 'Yes' },
  awfExtractionCompleted: { type: String, default: 'Yes' },
  extractedOutsideRelativity: { type: String, default: '' },
  txtStatus: { type: String, default: '' },
  entriesCompleted: { type: String, default: '' },
  reviewerNotes: { type: String, default: '' },
  familyGroup: { type: String, default: 'None' },
  persons: { type: [personSchema], default: [] },
}, { timestamps: true })

codingSchema.index({ projectId: 1, documentId: 1 }, { unique: true })

export default mongoose.models.Coding || mongoose.model('Coding', codingSchema)

